### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by assoft** [Tendoo/cms#1]
Setup Database (Step 2) -> Click "save settings"

URI: `http://tendoo.test/do-setup/app-details`

> Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required"

**Comment by Blair2004** [comment]
Can you provide a screenshot of the error ? From my side i'll proceed to deeper test. Thank you.

**Comment by Blair2004** [comment]
After deeper review, we've been facing that issue. But this issue is general to all Laravel installation. Actually the mail provider is not configured by default on Laravel installations.

**Comment by assoft** [comment]
Ohh sorry, worked after editing mail driver.
